#!/usr/bin/env perl
#
# Copied from Lab1/scripts/tmbBuild.sh and modified

$myname = "combineBuild";

$vecflags = "-mavx";

$cwd = `pwd`; chomp $cwd;
if (!($cwd =~ m|/code$|)) {
  die "$myname: Curdir should be the 'code' directory.\n";
}

$bin = "./cmb";
if (-e $bin) {
  unlink($bin);
}

$src = "test_combine8.c";
if(!(-f $src)) {
  die "$myname: Source file $src not found.\n";
}

for $type ("int", "float", "double") {
  system("gcc -O1 $vecflags -DDTYPE=$type $src -lrt -lm -o $bin");
  if (!(-x $bin)) {
    die "$myname: No binary $bin, compile error?\n";
  }
  system("$bin 0 64 50");
}


$ddir = "p1_data";
if(!(-d $ddir)) {
  system("mkdir $ddir");
}
$ncsv = (`ls *.csv | wc -l`) + 0;
if ($ncsv > 0) {
  system("mv *.csv $ddir");
} else {
  die "$myname: No .csv output files were produced.\n";
}

system("rm $bin");
