#!/usr/bin/env perl
#
# Copied from Lab1/scripts/tmbBuild.sh and modified

$myname = "dotBuild";

$cwd = `pwd`; chomp $cwd;
if (!($cwd =~ m|/code$|)) {
  die "$myname: Curdir should be the 'code' directory.\n";
}

$bin = "./td";
if (-e $bin) {
  unlink($bin);
}

$src = "test_dot8.c";
if(!(-f $src)) {
  die "$myname: Source file $src not found.\n";
}

for $type ("float", "double") {
  system("gcc -O1 -mavx -DDTYPE=$type $src -lrt -lm -o $bin");
  if (!(-x $bin)) {
    die "$myname: No binary $bin, compile error?\n";
  }
  # Test strange sizes
  for($DELTA=14; $DELTA<=17; $DELTA++) {
    $cmd = "$bin 0 $DELTA 10";
    print "$cmd\n";
    system($cmd);
  }
  # Bigger test for plotting
  system("$bin 0 64 50");
}

$ddir = "p1_data";
if(!(-d $ddir)) {
  system("mkdir $ddir");
}
$ncsv = (`ls *.csv | wc -l`) + 0;
if ($ncsv > 0) {
  system("mv *.csv $ddir");
} else {
  die "$myname: No .csv output files were produced.\n";
}

system("rm $bin");
