#!/usr/bin/env perl
#
# runAllTests  - run all the Lab3 scripts and display the tail end of
#                each of the CSV files with the largest ITERS

sub path_mtime
{
  my($path) = @_;
  return((stat($path))[9]);
}

sub runscr
{
  my($scr) = @_;

  $g_scr = $scr;
  die "$g_scr not executable!\n" if (!(-x $g_scr));
  $g_d1 = &path_mtime($g_scr);
  system("$g_scr");
}

sub showfile
{
  my($ofile) = @_;

  die "no output file $ofile!\n" if (!(-f $ofile));
  $d2 = &path_mtime($ofile);
  die "outpot $ofile not updated by $g_scr!\n" if ($d2 < $g_d1);
  print "--- $ofile\n";
  system("tail -5 $ofile");
}

# Check current directory
$cwd = `pwd`; chomp $cwd;
if (!($cwd =~ m|/code$|)) {
  die "$myname: Curdir should be the 'code' directory.\n";
}

# combine tests
&runscr("../scripts/combineBuild");
&showfile("p1_data/int_add_comb8_B0_D64_I50.csv");
&showfile("p1_data/float_add_comb8_B0_D64_I50.csv");
&showfile("p1_data/double_add_comb8_B0_D64_I50.csv");

# dot tests
&runscr("../scripts/dotBuild");
&showfile("p1_data/float_dot8_B0_D64_I50.csv");
&showfile("p1_data/double_dot8_B0_D64_I50.csv");

# intrinsics
&runscr("../scripts/intrinBuild");
&showfile("p2_data/floatMul_intrin_B0_D64_I50.csv");

# transpose
&runscr("../scripts/transposeBuild");
&showfile("p3_data/double_transpose_B0_D8_I100.csv");
