#!/bin/sh

OPT=-O1

gcc $OPT test_combine1-7.c -lrt -o tcmb && ./tcmb 0 5000 20
gcc $OPT test_combine1-7.c -S -o tcmb.s

gcc $OPT test_dot.c -lrt -o tdt && ./tdt
gcc $OPT test_dot.c -S -o tdt.s

gcc $OPT test_branch.c -lrt -o tbr && ./tbr
gcc $OPT test_branch.c -S -o tbr.s
